Further Align Various

diff --git a/.github/workflows/build_artefacts.yml b/.github/workflows/build_artefacts.yml
--- a/.github/workflows/build_artefacts.yml
+++ b/.github/workflows/build_artefacts.yml
@@ -69,9 +69,15 @@ jobs:
           mkdir -p "${ENV_BASE_DIR}" || exit 1
           cd "${ENV_BASE_DIR}" || exit 1
 
-          # Clone Repos
-          git clone "https://github.com/${ENV_REPO}.git" Working || exit 1
-          git clone "https://github.com/RefindPlusRepo/RefindPlusUDK.git" edk2 || exit 1
+          # Clone Refindplus Repo: Use Treeless Clone
+          # Has History (for '--contains' if used)
+          # REF: https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone
+          git clone --filter=tree:0 "https://github.com/${ENV_REPO}.git" Working || exit 1
+
+          # Clone EDK2 Repo: Use Shallow Clone
+          # Just a Build Dependency ... Minimal 'depth 1' Enough
+          # REF: https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone
+          git clone --depth 1 "https://github.com/RefindPlusRepo/RefindPlusUDK.git" edk2 || exit 1
 
       - name: Determine Target Branch
         shell: bash
@@ -85,6 +91,12 @@ jobs:
             echo "Find User Defined Branch via Commit ID"
             # Validate Input 'Commit ID'
             if [[ ! "${ENV_COMMIT_ID}" =~ ^[a-fA-F0-9]{7,40}$ ]]; then
+              echo "> [!CAUTION]" >> "${GITHUB_STEP_SUMMARY}"
+              echo "> Failed To Build RefindPlus." >> "${GITHUB_STEP_SUMMARY}"
+              echo "> See log on failed step for details." >> "${GITHUB_STEP_SUMMARY}"
+              echo "> Failed Step:- 'Make Binaries ... Determine Target Branch'" >> "${GITHUB_STEP_SUMMARY}"
+              echo "" >> "${GITHUB_STEP_SUMMARY}"
+
               echo "Error: Invalid Commit ID Format: '${ENV_COMMIT_ID}'"
               echo "       Must be Valid Git SHA (7-40 Hex Chars)"
               echo "       Exiting Now"
@@ -97,6 +109,12 @@ jobs:
             # Get Candidate Branches
             BranchList=$(git branch -r --contains "${ENV_COMMIT_ID}" | grep 'origin/' | sed 's|origin/||')
             if [[ -z "${BranchList}" ]]; then
+              echo "> [!CAUTION]" >> "${GITHUB_STEP_SUMMARY}"
+              echo "> Failed To Build RefindPlus." >> "${GITHUB_STEP_SUMMARY}"
+              echo "> See log on failed step for details." >> "${GITHUB_STEP_SUMMARY}"
+              echo "> Failed Step:- 'Make Binaries ... Determine Target Branch'" >> "${GITHUB_STEP_SUMMARY}"
+              echo "" >> "${GITHUB_STEP_SUMMARY}"
+
               echo "Error: Not Located on Any Branch: '${ENV_COMMIT_ID}'"
               echo "       Exiting Now"
               exit 1
@@ -105,6 +123,12 @@ jobs:
             # Use Target Branch Commit
             BRANCH=$(printf "%s\n" "${BranchList}" | head -n 1 | tr -d '[:space:]')
             if ! git show-ref --verify --quiet "refs/remotes/origin/${BRANCH}"; then
+              echo "> [!CAUTION]" >> "${GITHUB_STEP_SUMMARY}"
+              echo "> Failed To Build RefindPlus." >> "${GITHUB_STEP_SUMMARY}"
+              echo "> See log on failed step for details." >> "${GITHUB_STEP_SUMMARY}"
+              echo "> Failed Step:- 'Make Binaries ... Determine Target Branch'" >> "${GITHUB_STEP_SUMMARY}"
+              echo "" >> "${GITHUB_STEP_SUMMARY}"
+
               echo "Error: Remote Branch Not Found: '${BRANCH}'"
               echo "       Paranoia Check Failed!"
               echo "       Exiting Now"
@@ -196,6 +220,12 @@ jobs:
             PYTHON_URL="https://www.python.org/ftp/python/${PYTHON_VER}/${PYTHON_PKG}"
             printf "\nDownloading Python %s\n" "${PYTHON_VER}"
             curl --retry 3 --fail -O "${PYTHON_URL}" || {
+              echo "> [!CAUTION]" >> "${GITHUB_STEP_SUMMARY}"
+              echo "> Failed To Build RefindPlus." >> "${GITHUB_STEP_SUMMARY}"
+              echo "> See log on failed step for details." >> "${GITHUB_STEP_SUMMARY}"
+              echo "> Failed Step:- 'Make Binaries ... Apply Misc Prep'" >> "${GITHUB_STEP_SUMMARY}"
+              echo "" >> "${GITHUB_STEP_SUMMARY}"
+
               printf "\nERROR: Python %s Download Failed\n" "${PYTHON_VER}"
               exit 1
             }
@@ -203,6 +233,12 @@ jobs:
             printf "Verify Python %s Download\n" "${PYTHON_VER}"
             OBTAINED_HASH=$(md5 -q "${PYTHON_PKG}")
             if [[ "${OBTAINED_HASH}" != "${EXPECTED_HASH}" ]]; then
+              echo "> [!CAUTION]" >> "${GITHUB_STEP_SUMMARY}"
+              echo "> Failed To Build RefindPlus." >> "${GITHUB_STEP_SUMMARY}"
+              echo "> See log on failed step for details." >> "${GITHUB_STEP_SUMMARY}"
+              echo "> Failed Step:- 'Make Binaries ... Apply Misc Prep'" >> "${GITHUB_STEP_SUMMARY}"
+              echo "" >> "${GITHUB_STEP_SUMMARY}"
+
               echo "ERROR: Python Download Checksum Check Failure"
               echo "       Expected: ${EXPECTED_HASH}"
               echo "       Obtained: ${OBTAINED_HASH}"
@@ -220,11 +256,11 @@ jobs:
         shell: bash
         run: |
           # Main Build Script
-          export END_NOTICE='1'
+          export IS_REMOTE='1'
           cd "${ENV_BASE_DIR}/edk2/000-BuildScript" || exit 1
           chmod +x RefindPlusBuilder.sh
           ./RefindPlusBuilder.sh --build-type="${BUILD_FLAG}"
-          unset END_NOTICE
+          unset IS_REMOTE
 
 
         ###
@@ -278,14 +314,20 @@ jobs:
           echo "Portions Copyright 2006-2010 Christoph Pfisterer" >> "${GITHUB_STEP_SUMMARY}"
           echo "Portions Copyright The Intel Corporation & Others" >> "${GITHUB_STEP_SUMMARY}"
           echo "" >> "${GITHUB_STEP_SUMMARY}"
-          echo "RefindPlus is free software. You can modify and/or redistribute it" >> "${GITHUB_STEP_SUMMARY}"
-          echo "under the terms of the GNU General Public License published by the" >> "${GITHUB_STEP_SUMMARY}"
-          echo "Free Software Foundation. Either Version 3 of the license (GNU GPLv3)," >> "${GITHUB_STEP_SUMMARY}"
-          echo "or, at your option, any later version of the GNU General Public License." >> "${GITHUB_STEP_SUMMARY}"
+          echo "RefindPlus is free software. You can modify it and/or redistribute it" >> "${GITHUB_STEP_SUMMARY}"
+          echo "under the terms of the GNU General Public License as published by the" >> "${GITHUB_STEP_SUMMARY}"
+          echo "Free Software Foundation. Either version 3 of the License (GNU GPLv3)" >> "${GITHUB_STEP_SUMMARY}"
+          echo "or at your option, any later version of the License." >> "${GITHUB_STEP_SUMMARY}"
           echo "" >> "${GITHUB_STEP_SUMMARY}"
-          echo "GNU GPLv3 is supplied with this build." >> "${GITHUB_STEP_SUMMARY}"
-          echo "If missing, you can access a copy via this link:" >> "${GITHUB_STEP_SUMMARY}"
+          echo "RefindPlus is distributed in the hope that it will be useful," >> "${GITHUB_STEP_SUMMARY}"
+          echo "but WITHOUT ANY WARRANTY; without even the implied warranty" >> "${GITHUB_STEP_SUMMARY}"
+          echo "of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE." >> "${GITHUB_STEP_SUMMARY}"
+          echo "See the GNU General Public License for more details." >> "${GITHUB_STEP_SUMMARY}"
+          echo "" >> "${GITHUB_STEP_SUMMARY}"
+          echo "A copy of GNU GPLv3 is supplied with this build." >> "${GITHUB_STEP_SUMMARY}"
+          echo "If missing, you can access copies at the links below:" >> "${GITHUB_STEP_SUMMARY}"
           echo "<https://github.com/RefindPlusRepo/RefindPlus/blob/GOPFix/LICENSE.txt>" >> "${GITHUB_STEP_SUMMARY}"
+          echo "<https://www.gnu.org/licenses/gpl-3.0.en.html>" >> "${GITHUB_STEP_SUMMARY}"
 
           echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
           echo "---" >> "${GITHUB_STEP_SUMMARY}"
@@ -293,10 +335,28 @@ jobs:
 
           echo "> [!NOTE]" >> "${GITHUB_STEP_SUMMARY}"
           echo "> Output files have the form: \`[METADATA]---[FILENAME].efi\`." >> "${GITHUB_STEP_SUMMARY}"
-          echo "> It is anticipated the metadata will be removed before use." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> It is anticipated the metadata will be discarded before use." >> "${GITHUB_STEP_SUMMARY}"
+          echo "" >> "${GITHUB_STEP_SUMMARY}"
+
           echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
           echo "---" >> "${GITHUB_STEP_SUMMARY}"
           echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
+
+          echo "> [!IMPORTANT]" >> "${GITHUB_STEP_SUMMARY}"
+          echo "> Output files with \`BLB_xx_???\` in their filename metadata ARE NOT part of RefindPlus." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> These are binaries bundled with RefindPlusUDK and are provided as convenience items." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> These binary blobs WERE NOT built on RefindPlus code and were developed by others." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> These binary blobs are separately licensed by their actual respective developers." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> **x64_shell.efi**: From OpenCore (OpenShell) ... BSD 3-Clause License." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> **x64_CleanNvram.efi**: From OpenCore ... BSD 3-Clause License." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> **x64_memtest86p.efi**: From memtest.org ... GNU GPLv2 License." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> **x64_gdisk.efi**: From Roderick Smith ... GNU GPLv2 License." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> **x64_ipxe.efi**: From ipxe.org ... GNU GPLv2 License." >> "${GITHUB_STEP_SUMMARY}"
+          echo "" >> "${GITHUB_STEP_SUMMARY}"
+
+          echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
+          echo ". . ." >> "${GITHUB_STEP_SUMMARY}"
+
 
   sign-binaries:
     name: Sign Binaries
@@ -304,6 +364,34 @@ jobs:
     if: ${{ github.event.inputs.sign_output == 'YES' }}
     runs-on: ubuntu-latest
     steps:
+      - name: Prep Steps
+        shell: bash
+        run: |
+          # Prepare Summmary
+          echo "# RefindPlus ... A Boot Manager for Mac and PC" > "${GITHUB_STEP_SUMMARY}"
+          echo "" >> "${GITHUB_STEP_SUMMARY}"
+          echo "Copyright 2020-2026 Dayo Akanji" >> "${GITHUB_STEP_SUMMARY}"
+          echo "sf.net/u/dakanji/profile" >> "${GITHUB_STEP_SUMMARY}"
+          echo "" >> "${GITHUB_STEP_SUMMARY}"
+          echo "Portions Copyright 2012-2024 Roderick W. Smith" >> "${GITHUB_STEP_SUMMARY}"
+          echo "Portions Copyright 2006-2010 Christoph Pfisterer" >> "${GITHUB_STEP_SUMMARY}"
+          echo "Portions Copyright The Intel Corporation & Others" >> "${GITHUB_STEP_SUMMARY}"
+          echo "" >> "${GITHUB_STEP_SUMMARY}"
+          echo "RefindPlus is free software. You can modify it and/or redistribute it" >> "${GITHUB_STEP_SUMMARY}"
+          echo "under the terms of the GNU General Public License as published by the" >> "${GITHUB_STEP_SUMMARY}"
+          echo "Free Software Foundation. Either version 3 of the License (GNU GPLv3)" >> "${GITHUB_STEP_SUMMARY}"
+          echo "or at your option, any later version of the License." >> "${GITHUB_STEP_SUMMARY}"
+          echo "" >> "${GITHUB_STEP_SUMMARY}"
+          echo "RefindPlus is distributed in the hope that it will be useful," >> "${GITHUB_STEP_SUMMARY}"
+          echo "but WITHOUT ANY WARRANTY; without even the implied warranty" >> "${GITHUB_STEP_SUMMARY}"
+          echo "of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE." >> "${GITHUB_STEP_SUMMARY}"
+          echo "See the GNU General Public License for more details." >> "${GITHUB_STEP_SUMMARY}"
+          echo "" >> "${GITHUB_STEP_SUMMARY}"
+          echo "A copy of GNU GPLv3 is supplied with this build." >> "${GITHUB_STEP_SUMMARY}"
+          echo "If missing, you can access copies at the links below:" >> "${GITHUB_STEP_SUMMARY}"
+          echo "<https://github.com/RefindPlusRepo/RefindPlus/blob/GOPFix/LICENSE.txt>" >> "${GITHUB_STEP_SUMMARY}"
+          echo "<https://www.gnu.org/licenses/gpl-3.0.en.html>" >> "${GITHUB_STEP_SUMMARY}"
+
       - name: Validate Repository Secrets
         shell: bash
         env:
@@ -317,6 +405,16 @@ jobs:
           [[ -n "${INPUT_CER}" &&  -z "${INPUT_CRT}" && "${NO_CRT}" == "0" ]] && NO_CRT=1 || true
 
           if (( NO_KEY || NO_CRT )); then
+            echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
+            echo "---" >> "${GITHUB_STEP_SUMMARY}"
+            echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
+
+            echo "> [!CAUTION]" >> "${GITHUB_STEP_SUMMARY}"
+            echo "> The Artefacts HAVE NOT been Signed." >> "${GITHUB_STEP_SUMMARY}"
+            echo "> See log on failed step for details." >> "${GITHUB_STEP_SUMMARY}"
+            echo "> Failed Step:- 'Sign Binaries ... Validate Repository Secrets'" >> "${GITHUB_STEP_SUMMARY}"
+            echo "" >> "${GITHUB_STEP_SUMMARY}"
+
             echo "ERROR: Invalid Repository Secrets Setup for Secure Boot Signing"
 
             (( NO_KEY )) && echo "       The required 'SIG_RP_KEY' repository secret is missing" || true
@@ -327,23 +425,6 @@ jobs:
             exit 1
           fi
 
-          echo "# RefindPlus ... A Boot Manager for Mac and PC" > "${GITHUB_STEP_SUMMARY}"
-          echo "" >> "${GITHUB_STEP_SUMMARY}"
-          echo "Copyright 2020-2026 Dayo Akanji" >> "${GITHUB_STEP_SUMMARY}"
-          echo "sf.net/u/dakanji/profile" >> "${GITHUB_STEP_SUMMARY}"
-          echo "" >> "${GITHUB_STEP_SUMMARY}"
-          echo "Portions Copyright 2012-2024 Roderick W. Smith" >> "${GITHUB_STEP_SUMMARY}"
-          echo "Portions Copyright 2006-2010 Christoph Pfisterer" >> "${GITHUB_STEP_SUMMARY}"
-          echo "Portions Copyright The Intel Corporation & Others" >> "${GITHUB_STEP_SUMMARY}"
-          echo "" >> "${GITHUB_STEP_SUMMARY}"
-          echo "RefindPlus is free software. You can modify and/or redistribute it" >> "${GITHUB_STEP_SUMMARY}"
-          echo "under the terms of the GNU General Public License published by the" >> "${GITHUB_STEP_SUMMARY}"
-          echo "Free Software Foundation. Either Version 3 of the license (GNU GPLv3)," >> "${GITHUB_STEP_SUMMARY}"
-          echo "or, at your option, any later version of the GNU General Public License." >> "${GITHUB_STEP_SUMMARY}"
-          echo "" >> "${GITHUB_STEP_SUMMARY}"
-          echo "GNU GPLv3 is supplied with this build." >> "${GITHUB_STEP_SUMMARY}"
-          echo "If missing, you can access a copy via this link:" >> "${GITHUB_STEP_SUMMARY}"
-          echo "<https://github.com/RefindPlusRepo/RefindPlus/blob/GOPFix/LICENSE.txt>" >> "${GITHUB_STEP_SUMMARY}"
 
       - name: Fetch Interim Artefact (REL)
         if: contains(github.event.inputs.build_type, 'REL')
@@ -409,11 +490,11 @@ jobs:
             echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
 
             echo "> [!IMPORTANT]" >> "${GITHUB_STEP_SUMMARY}"
-            echo "> A one-off private key was used to sign artefacts.  " >> "${GITHUB_STEP_SUMMARY}"
+            echo "> A one-off private key was used to sign the artefacts.  " >> "${GITHUB_STEP_SUMMARY}"
             echo "> This key was discarded as cannot be securely transferred.  " >> "${GITHUB_STEP_SUMMARY}"
             echo "> Hence, the certificate can only be used for this specific build.  " >> "${GITHUB_STEP_SUMMARY}"
             echo "" >> "${GITHUB_STEP_SUMMARY}"
-            echo "See [RefindPlus Documentation](https://github.com/RefindPlusRepos/RefindPlus/blob/GOPFix/BUILDING.md) on how to supply reusable credentials." >> "${GITHUB_STEP_SUMMARY}"
+            echo "See [RefindPlus Documentation](https://github.com/RefindPlusRepos/RefindPlus/blob/GOPFix/BUILDING.md) for how to supply reusable credentials." >> "${GITHUB_STEP_SUMMARY}"
           fi
 
           if [[ -f "${ENV_USER_CRT}" && (-z "${ENV_USER_CER}" || ! -f "${ENV_USER_CER}") ]]; then
@@ -440,6 +521,21 @@ jobs:
           ###
           # Apply signature to specified item
           ###
+          do_summary() {
+            echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
+            echo "---" >> "${GITHUB_STEP_SUMMARY}"
+            echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
+
+            echo "> [!CAUTION]" >> "${GITHUB_STEP_SUMMARY}"
+            echo "> The Artefacts HAVE NOT been Signed." >> "${GITHUB_STEP_SUMMARY}"
+            echo "> See the failed step log for details." >> "${GITHUB_STEP_SUMMARY}"
+            echo "> Failed Step:- 'Sign Binaries ... Sign Requested Binaries'" >> "${GITHUB_STEP_SUMMARY}"
+            echo "" >> "${GITHUB_STEP_SUMMARY}"
+          }
+
+          ###
+          # Apply signature to specified item
+          ###
           sign_the_item() {
             local file_in="${1}"
             local file_out="${2}"
@@ -448,6 +544,8 @@ jobs:
             sbsign --key "${PATH_KEY}" \
                    --cert "${PATH_CRT}" \
                    --output "${file_out}" "${file_in}" || {
+              do_summary ;
+
               echo "ERROR: Failed While Signing ${file_in}"
               echo "       Unsigned Artefacts Saved with Prefix: 'NOT_SIGNED---'"
               echo "       Exiting Now"
@@ -487,6 +585,8 @@ jobs:
               outfile="${dir_out}/SIGNED_${FLAG_NOW}-${base}.efi"
 
               if [[ ! -f "${infile}" ]]; then
+                do_summary ;
+
                 echo "ERROR: Main Binary Not Found: 'x64_${name_tag}.efi'"
                 echo "       Unsigned Artefacts Saved with Prefix: 'NOT_SIGNED---'"
                 echo "       Exiting Now"
@@ -517,7 +617,7 @@ jobs:
 
             # Sign Misc Blobs
             printf '\nSign Misc Blobs...\n'
-            for name_tag in shell memtest86 gdisk CleanNvram ipxe; do
+            for name_tag in shell memtest86p gdisk CleanNvram ipxe; do
               base="BLB_xx_${target}---x64_${name_tag}"
               infile="${dir_in}/${base}.efi"
               outfile="${dir_out}/SIGNED_${FLAG_NOW}-${base}.efi"
@@ -693,7 +793,24 @@ jobs:
 
           echo "> [!NOTE]" >> "${GITHUB_STEP_SUMMARY}"
           echo "> Output files have the form: \`[METADATA]---[FILENAME].efi\`." >> "${GITHUB_STEP_SUMMARY}"
-          echo "> It is anticipated the metadata will be removed before use." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> It is anticipated the metadata will be discarded before use." >> "${GITHUB_STEP_SUMMARY}"
+          echo "" >> "${GITHUB_STEP_SUMMARY}"
+
           echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
           echo "---" >> "${GITHUB_STEP_SUMMARY}"
           echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
+
+          echo "> [!IMPORTANT]" >> "${GITHUB_STEP_SUMMARY}"
+          echo "> Output files with \`BLB_xx_???\` in their filename metadata ARE NOT part of RefindPlus." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> These are binaries bundled with RefindPlusUDK and are provided as convenience items." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> These binary blobs WERE NOT built on RefindPlus code and were developed by others." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> These binary blobs are separately licensed by their actual respective developers." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> **x64_shell.efi**: From OpenCore (OpenShell) ... BSD 3-Clause License." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> **x64_CleanNvram.efi**: From OpenCore ... BSD 3-Clause License." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> **x64_memtest86p.efi**: From memtest.org ... GNU GPLv2 License." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> **x64_gdisk.efi**: From Roderick Smith ... GNU GPLv2 License." >> "${GITHUB_STEP_SUMMARY}"
+          echo "> **x64_ipxe.efi**: From ipxe.org ... GNU GPLv2 License." >> "${GITHUB_STEP_SUMMARY}"
+
+          echo "" >> "${GITHUB_STEP_SUMMARY}"
+          echo "<br><br>" >> "${GITHUB_STEP_SUMMARY}"
+          echo ". . ." >> "${GITHUB_STEP_SUMMARY}"
